### ISSUE TITLE
Would you consider MIT?

### ISSUE THREAD

**Issue by reZach** [moloch--/reasonably-secure-electron#3]
Hello @moloch--,

I'm the maintainer of https://github.com/reZach/secure-electron-template as you may know and I'm reaching out to ask if you'll consider changing the license of one of your files in this repository to MIT? The file in question is in regards to your `protocol.js` (https://github.com/reZach/secure-electron-template/blob/master/app/electron/protocol.js).

First, I just have to say thank you for providing your insight and input into your work on this repository. I think it is absolutely great and I think the repository is better off with your change, because it seems a lot of people [have the same questions](https://github.com/electron/electron/issues/12011) on how to implement what you set up.

I am reaching out not to say I'd like to ask if the license can be changed because I want to make money on this template. In fact, I've actually made more changes than I'd ever thought I would and it is a fun hobby from time to time to maintain the template. I'm reaching out to ask because I feel the template would have more adoption with a less-restrictive license.

Of course, you have _no_ obligation to this request, and I _do_ appreciate your contribution to help make electron apps more secure. If you _were_ considering it, I was toying around with the idea to send you a one-time Github sponsors payment, in thanks for the many forks/uses of the template to-date.

Thanks,
reZach

**Comment by moloch--** [comment]
Shouldn't be a problem

**Comment by reZach** [comment]
Great, thanks @moloch--!

I think then I'll change the license within that file and we should be good, thanks again!

**Comment by moloch--** [comment]
@reZach Fixed.
